### ISSUE TITLE
Auto start recording on power-on

### ISSUE THREAD

**Issue by lesmo** [funneld/XiaomiYi#1]
Is there a way to make the Yi start recording once it's powered on with an `autoexec.ash`?

**Comment by CrazyCoder** [comment]
There is:

```
#AUTOREC script by nutsey
sleep 10
t app key record 
```

**Comment by lesmo** [comment]
Now that is a beautiful script. Thanks!!

**Comment by lesmo** [comment]
Wait.. uh, I'm not sure if I did something wrong but... apparently it's not working. I just tested it, and the camera does not appear to start the recording. I get no feedback of it, and when I checked the SD Card there was no video.

I tested if it was being executed by adding a beep command, but it wasn't executed either. I guess I'm missing something? AFAIK it's just writing the script, and then saving it to the root of the SD.

**Comment by CrazyCoder** [comment]
Try increasing the delay. Does it beep if you add it just after sleep? Make sure the file name is correct.
